spring.application.name=hello-Spring
spring.datasource.url=jdbc:mysql://localhost:3306/DonDoc
spring.datasource.username=root
spring.datasource.password=soonja0811
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
//DB???_???_??_????????